config/routes.rb
Dmtrails::Application.routes.draw do

  get "microposts/create"

  get "microposts/destroy"

  resources :gravatar, :only => [:edit, :update]

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]  

  match '/signup' , :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
    
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  root :to => "pages#home"
  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user
  default_scope :order => "microposts.created_at DESC"

  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true
end

app/models/user.rb
require 'digest'

# == Schema Information
# Schema version: 20110517152315
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  attr_accessor :password
  
  has_many :microposts, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,    :presence => true,
                      :length => {:maximum => 50}
  validates :email,   :presence => true,
                      :format => { :with => email_regex },
                      :uniqueness => { :case_sensitive => false }
                      
  validates :password,:presence =>true,
                      :confirmation => true,
                      :length => { :within => 5..40 }


  before_save :encrypt_password

  def has_password?(clear_password)
    encrypted_password == encrypt(clear_password)
  end
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    user && user.has_password?(submitted_password) ? user : nil
  end
  def self.authenticate_with_salt(id,cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end  
  def feed
    Micropost.where("user_id = ?", id)
  end
  private
     
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end    
    def make_salt
      secure_hash("#{Time.now.utc}--{password}")
    end
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  private
    def authenticate
      deny_access unless signed_in?
    end  
    def anonymous
      redirect_to root_path unless !signed_in?
    end  
    def admin_user
      redirect_to root_path unless admin?
    end  
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user? @user
    end  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate
  before_filter :authorized_user, :only => [:destroy]

  def create
    @micropost = current_user.microposts.build params[:micropost]
    if(@micropost.save)
      flash[:success] = 'Post created'
      redirect_to root_path
    else
      @title = "Home"
      @feed_items = []
      render 'pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end

  private
  def authorized_user
   @micropost = Micropost.find(params[:id])
   redirect_to root_path unless current_user?@micropost.user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
    if signed_in?
      @micropost = Micropost.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                        params[:session][:password])

    if user.nil?
      flash.now[:error]="Invalid login/password"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end    

  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update] 
  before_filter :correct_user, :only => [:edit, :update] 
  before_filter :admin_user,   :only => [:destroy] 
  before_filter :anonymous,    :only => [:new, :create]
  def index
    @title = "All users"
    @users = User.paginate( :page=>params[:page] )
  end  

  def show
    @user = User.find(params[:id])
    @title = @user.name
    @microposts = @user.microposts.paginate(:page => params[:page])
  end
    
  def new
    @title = "Sign up"
    @user = User.new
  end
  def edit
    @title = "Edit user"
  end  
  def update
    if(@user.update_attributes(params[:user]))
      flash[:success] = "Profile updated"
      redirect_to @user
    else  
      @title = "Edit user"
      render :edit
    end  
  end  
  def create
    @user = User.new params[:user]
    
    if(@user.save)
      flash[:success] = 'welcome to the sample app'
      sign_in @user
      redirect_to @user
    else
      @user.password=""
      @user.password_confirmation=""
      @title = 'Sign up'
      render :new
    end      
  end

  def destroy
    user = User.find(params[:id])
    if current_user? user
      redirect_to root_path
    else
      user.destroy
      flash[:success]= "User deleted"
      redirect_to users_path
    end  
  end  
  
  
  private
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end  
  end
  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end  
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:remember_token] = user.id
    self.current_user = user
  end
  def sign_out
    session[:remember_token] = nil
    self.current_user = nil
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user  
    @current_user ||= user_from_remember_token
  end
  def current_user?(user)
    current_user == user
  end
  def admin?
    current_user.admin?
  end  
  def deny_access
    store_path
    redirect_to signin_path, :notice => "You must sign in to access this page"
  end
  def redirect_back_or(path)
    redirect_to(session[:originpath] || path)
    clear_originpath
  end      
  private
  def clear_originpath
    session[:originpath] = nil
  end  
  def store_path
    session[:originpath] = request.fullpath
  end
  def user_from_remember_token
    User.find_by_id(remember_token)
  end  
  def remember_token
    session[:remember_token] || nil
  end

  def signed_in?
    !current_user.nil?
  end  
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50})
    gravatar_image_tag  user.email.downcase , 
                        :alt => user.name,
                        :class => 'gravatar',
                        :gravatar => options
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to logo, root_path %></h1>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Users", users_path %></li>      
      <li><%= link_to "Profile", current_user %>
      <li><%= link_to "Settings", edit_user_path(current_user) %>  
      <li><%= link_to "Sign out", signout_path, :method=>:delete %></li>

      <% else %>        
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
<section class="round" id="flashmessages">
  <% flash.each do |key, value| %>
     <%= content_tag(:div, value, :class => "#{key}") %>
   <% end %>
</section>
<% end %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/messages' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= javascript_include_tag :defaults %>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
<span class="content">
  <%= micropost.content %>
</span>
<date><%= time_ago_in_words(micropost.created_at) %></date>
<% if current_user? micropost.user %>
  <%= link_to 'Delete', micropost, :method => :delete, :confirm => 'Sure ?' %>
<% end %>
</li>

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>

app/views/pages/_home.notsignedin.html.erb
  <p>
  <%= link_to "Sign up now", signup_path, :class => "signup_button round" %>
  </p>  

app/views/pages/_home.signedin.html.erb
  <h1>What's up ?</h1>
  <div class="form">
    <%= render 'shared/micropost_form' %>
  </div>
  <div class="info">
    <%= render 'shared/userinfo', :user => current_user %>
  </div>
  <% unless @feed_items.empty? %>
    <ol class="feed">
      <%= render :partial=>"shared/feed_item", :collection => @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
  <% end %>

app/views/pages/about.html.erb
    <h1>About Us</h1>
    <p>
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>
      Contact Ruby on Rails Tutorial about the sample app at the
      <a href="http://railstutorial.org/feedback">feedback page</a>.
    </p>

app/views/pages/help.html.erb
<h1>Help page !</h1>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</p>

<% if signed_in? %>
  <%= render 'pages/home.signedin' %>
<% else %>  
  <%= render 'pages/home.notsignedin' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
       prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
 </div>  
<% end %>  

app/views/shared/_feed_item.html.erb
<li>
<span class="avatar">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
</span>
<span class="user">
  <%= link_to feed_item.user.name, feed_item.user %>
</span>
<date><%= time_ago_in_words(feed_item.created_at) %> ago</date>
<% if current_user? feed_item.user %>
  <%= link_to "delete", feed_item, :method => :delete, :confirm => 'are you sure ?' %>
<% end %>
<span class="content">
<%= feed_item.content %>
</span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => @micropost %>
  <div class="field">
    <%= f.text_area :content , :class => :countable %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>  

app/views/shared/_userinfo.html.erb
<aside>
Name: <%= user.name %><br />
URL : <%= link_to user_path(user), user  %>
<%= pluralize(user.microposts.count, "microposts") %>
</aside>

app/views/users/_form.html.erb
<%= form_for @user do |f|%>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>  
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>  
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>  
  <div class="field">
    <%= f.label :password_confirmation,'Confirmation' %>
    <%= f.password_field :password_confirmation %>
  </div>  
  <div class="actions">
    <%= f.submit "Sign up", :disable_with => 'Signing up...' %>
  </div>  
<% end%>

app/views/users/_micropost.html.erb
<span class="content">
  <%= micropost.content %>
</span>
<date><%= micropost.created_at %></date>

app/views/users/_user.html.erb
<li><%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && user != current_user %>
       | <%= link_to('Delete', user, :method => :delete, :confirm=>"Are you sure?", :title=>"Delete #{user.name}") %>
      <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user <%= @user.name %></h1>
<%= render 'users/form' %>
<%= gravatar_for @user %>
<%= link_to "change", gravatar_url %>

app/views/users/index.html.erb
<h1>Users list</h1>

<%= will_paginate %>
<ul>
  <%= render @users %>
</ul>  

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>


<%= render 'users/form' %>

app/views/users/show.html.erb
<%= render 'shared/userinfo', :user => @user %>
<h1><%= gravatar_for @user %><%= @user.name %></h1>
<% unless @user.microposts.empty? %>
  <%= will_paginate @microposts %>
<ul class="microposts">
  <%= render @microposts %>
</ul>
<% end %>